version: '3.8'

volumes:
  mysql-volume:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./src/:/var/www/html
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
    environment:
      - MYSQL_ATTR_SSL_CA=${PS_MYSQL_CA_CERT_PATH}
    user: www-data

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html