name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        # HOST: ${{ secrets.EC2_HOST }}
        # USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        echo "Project Name:  ${{ secrets.PROJECT_NAME }} "
        ssh -v -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.$USER }}@${{ secrets.$HOST }} "cd ${{ secrets.PROJECT_NAME }} && git pull"